In [78]:
#imports
import math
import numpy as np
import random

In [79]:
#constants
D=10**6  #Bandwodth
N= -174+10*(math.log10(D))  #Noise in DBM
N_linear=(N)*(10**(-3))*(10**(N/10))    #Noise in miliwatt


In [80]:
#variables
T=4  #Transimitting antenna  M
R=4  #Receiving antennas  N

In [93]:
#converting Powers {0,2,4}dbm to watt  rounded to 4 decimal palce
watt1 =round(10 ** (0 / 10) * 0.001, 4) 
watt2 = round(10 ** (2 / 10) * 0.001, 4)
watt3 = round(10 ** (4 / 10) * 0.001,4)
mylist=[watt1,watt2,watt3]
print(mylist)


[0.001, 0.0016, 0.0025]


In [95]:
#creating scenarios in watt
n=1
def create_random_matrix(rows, columns):
    matrix = [[random.choice(mylist) for _ in range(columns)] for _ in range(rows)]
    return matrix
rows = 81
columns = 4
random_matrix = create_random_matrix(rows, columns)  #the matrix

random_matrix_array=np.array(random_matrix)  #converting the matrix to array
print(random_matrix_array)





[[0.0025 0.0016 0.0016 0.001 ]
 [0.0016 0.0025 0.0025 0.0025]
 [0.001  0.0025 0.001  0.001 ]
 [0.0025 0.0016 0.0016 0.001 ]
 [0.0025 0.001  0.001  0.0025]
 [0.001  0.0016 0.0025 0.0016]
 [0.0025 0.0025 0.001  0.0016]
 [0.001  0.001  0.0016 0.0025]
 [0.0025 0.0025 0.0025 0.0016]
 [0.001  0.0016 0.0025 0.0025]
 [0.001  0.001  0.001  0.001 ]
 [0.0025 0.0016 0.0016 0.0025]
 [0.001  0.0016 0.001  0.0025]
 [0.001  0.001  0.0025 0.001 ]
 [0.0025 0.0025 0.001  0.001 ]
 [0.001  0.0016 0.0025 0.0025]
 [0.001  0.0016 0.0025 0.0016]
 [0.0025 0.0025 0.0016 0.001 ]
 [0.0016 0.0016 0.0016 0.001 ]
 [0.0025 0.001  0.0016 0.0025]
 [0.0025 0.0016 0.001  0.001 ]
 [0.0016 0.0025 0.0016 0.001 ]
 [0.0016 0.0016 0.001  0.0016]
 [0.0025 0.001  0.0016 0.001 ]
 [0.0025 0.0016 0.0025 0.0016]
 [0.001  0.0016 0.001  0.0025]
 [0.0016 0.001  0.0025 0.0016]
 [0.001  0.001  0.0025 0.001 ]
 [0.0016 0.0016 0.0025 0.0016]
 [0.001  0.0025 0.001  0.0016]
 [0.0025 0.001  0.0025 0.0025]
 [0.0016 0.001  0.0016 0.001 ]
 [0.001 

In [96]:
def channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users):
    channel_matrix = np.zeros((num_users, num_BS_antenna), dtype=complex)
    
    for i in range(num_users):
        d = random.randint(min_distance, max_distance)  # random distance
        path_loss_factor = d ** (-loss)
        
        for j in range(num_BS_antenna):
            channel_coefficient = path_loss_factor * (np.random.randn() + 1j * np.random.randn()) / np.sqrt(2)
            channel_matrix[i][j] = channel_coefficient
            
    gain_matrix = np.abs(channel_matrix) ** 2
    return channel_matrix, gain_matrix

# Example usage
min_distance = 500
max_distance = 1000
loss = 4
num_BS_antenna = 4
num_users = 4

channel_mat, gain_matrix = channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users)

channel_mat_array=np.array(channel_mat)  #matrix
print("Channel matrix:\n", channel_mat_array)   #converting the matrix to array

gain_matrix_array=np.array(gain_matrix)   #matrix
print("Gain matrix:\n", gain_matrix_array)     #converting the matrix to array





Channel matrix:
 [[ 2.06457536e-12+5.84584151e-13j  1.33017154e-12-7.53754914e-13j
  -9.16240328e-13-1.86154106e-13j  1.28660493e-13-1.69024214e-13j]
 [ 3.42893589e-12-2.90461021e-12j  4.12690587e-13+4.66709954e-13j
  -1.33550083e-12-2.13232214e-12j  2.74154610e-12+1.09157977e-12j]
 [-2.91604498e-12+1.85820446e-12j  9.59878445e-13-4.30585001e-12j
   2.24821026e-12-6.10939628e-13j -2.22110155e-12-1.22086403e-12j]
 [-3.98190141e-13+3.66973983e-12j -3.50815315e-13+1.90876209e-13j
  -2.25355354e-12-1.75448052e-12j  2.42084904e-12+9.02568416e-13j]]
Gain matrix:
 [[4.60421005e-24 2.33750280e-24 8.74149690e-25 4.51227075e-26]
 [2.01943618e-23 3.88131702e-25 6.33036017e-24 8.70762143e-24]
 [1.19562422e-23 1.94617109e-23 5.42769660e-24 6.42380106e-24]
 [1.36255458e-23 1.59505113e-25 8.15670545e-24 6.67513984e-24]]


In [97]:
first_row_random_matrix_array = random_matrix_array[0]
print (first_row_random_matrix_array)


[0.0025 0.0016 0.0016 0.001 ]


In [98]:
result_matrix = gain_matrix_array * first_row_random_matrix_array
print (result_matrix)

[[1.15105251e-26 3.74000448e-27 1.39863950e-27 4.51227075e-29]
 [5.04859046e-26 6.21010723e-28 1.01285763e-26 8.70762143e-27]
 [2.98906054e-26 3.11387375e-26 8.68431456e-27 6.42380106e-27]
 [3.40638645e-26 2.55208180e-28 1.30507287e-26 6.67513984e-27]]
