In [202]:
#imports
import math
import numpy as np
import random

In [192]:
#constants
D=10**6  #Bandwodth
N= -174+10*(math.log10(D))  #Noise in DBM
N_linear=(N)*(10**(-3))*(10**(N/10))    #Noise in miliwatt


In [193]:
#variables
T=4  #Transimitting antenna  M
R=4  #Receiving antennas  N

In [194]:
#converting Powers {0,2,4}dbm to watt  rounded to 4 decimal palce
watt1 =round(10 ** (0 / 10) * 0.001, 4) 
watt2 = round(10 ** (2 / 10) * 0.001, 4)
watt3 = round(10 ** (4 / 10) * 0.001,4)
mylist=[watt1,watt2,watt3]
print(mylist)


[0.001, 0.0016, 0.0025]


In [195]:
#creating scenarios in watt
n=1
def create_random_matrix(rows, columns):
    matrix = [[random.choice(mylist) for _ in range(columns)] for _ in range(rows)]
    return matrix
rows = 81
columns = 4
random_matrix = create_random_matrix(rows, columns)  #the matrix

random_matrix_array=np.array(random_matrix)  #converting the matrix to array
print(random_matrix_array)





[[0.0016 0.0016 0.0025 0.0016]
 [0.0025 0.0025 0.001  0.0016]
 [0.0025 0.0025 0.001  0.0016]
 [0.001  0.001  0.0016 0.0016]
 [0.001  0.001  0.0016 0.001 ]
 [0.0025 0.001  0.001  0.001 ]
 [0.001  0.001  0.001  0.001 ]
 [0.0025 0.0025 0.0025 0.0025]
 [0.0025 0.0016 0.001  0.0016]
 [0.0025 0.0025 0.0025 0.0025]
 [0.001  0.0025 0.001  0.001 ]
 [0.0016 0.001  0.001  0.0016]
 [0.0016 0.001  0.0025 0.0016]
 [0.0025 0.0016 0.001  0.0016]
 [0.001  0.0025 0.0025 0.0016]
 [0.0016 0.0016 0.0025 0.001 ]
 [0.0025 0.0016 0.0016 0.001 ]
 [0.0016 0.001  0.0025 0.001 ]
 [0.0016 0.0025 0.001  0.001 ]
 [0.0016 0.0016 0.001  0.0016]
 [0.0016 0.001  0.0016 0.0025]
 [0.001  0.0016 0.0025 0.0016]
 [0.0025 0.001  0.0025 0.0025]
 [0.0016 0.0016 0.0016 0.001 ]
 [0.0016 0.001  0.0016 0.001 ]
 [0.0025 0.0016 0.0025 0.0025]
 [0.001  0.0016 0.0016 0.001 ]
 [0.0016 0.0016 0.001  0.0025]
 [0.0016 0.0025 0.0016 0.0025]
 [0.001  0.0025 0.0016 0.0016]
 [0.0025 0.0016 0.001  0.0025]
 [0.001  0.001  0.0025 0.0016]
 [0.0025

In [196]:
def channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users):
    channel_matrix = np.zeros((num_users, num_BS_antenna), dtype=complex)
    
    for i in range(num_users):
        d = random.randint(min_distance, max_distance)  # random distance
        path_loss_factor = d ** (-loss)
        
        for j in range(num_BS_antenna):
            channel_coefficient = path_loss_factor * (np.random.randn() + 1j * np.random.randn()) / np.sqrt(2)
            channel_matrix[i][j] = channel_coefficient
            
    gain_matrix = np.abs(channel_matrix) ** 2
    return channel_matrix, gain_matrix

# Example usage
min_distance = 500
max_distance = 1000
loss = 4
num_BS_antenna = 4
num_users = 4

channel_mat, gain_matrix = channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users)

channel_mat_array=np.array(channel_mat)  #matrix
print("Channel matrix:\n", channel_mat_array)   #converting the matrix to array

gain_matrix_array=np.array(gain_matrix)   #matrix
print("Gain matrix:\n", gain_matrix_array)     #converting the matrix to array





Channel matrix:
 [[ 9.44958438e-13-1.22323791e-12j -2.97565023e-12+8.73968870e-13j
  -5.82131132e-12-2.78884164e-12j -1.21574968e-13+4.71490452e-12j]
 [ 2.04421805e-12+2.74950897e-12j  1.38375696e-12+2.02474404e-12j
   5.81007335e-12-3.37371062e-12j  4.43596996e-12-6.90166372e-12j]
 [-2.46982917e-12-2.05079868e-12j  1.10269965e-13-3.72477730e-13j
  -2.73843155e-12-1.43145550e-12j  1.89708610e-12-6.56721185e-13j]
 [ 1.59500603e-12+4.89378226e-13j -8.62407058e-13+8.83385486e-13j
   1.60368158e-13+4.83203196e-13j  1.12611106e-13-1.38001383e-13j]]
Gain matrix:
 [[2.38925742e-24 9.61831586e-24 4.16653032e-23 2.22451051e-23]
 [1.17386270e-23 6.01437175e-24 4.51388756e-23 6.73107916e-23]
 [1.03058314e-23 1.50899125e-25 9.54807222e-24 4.03021837e-24]
 [2.78353530e-24 1.52411585e-24 2.59203274e-25 3.17256429e-26]]


In [197]:
first_row_random_matrix_array = random_matrix_array[0][0]
print (first_row_random_matrix_array)


0.0016


In [201]:
for j in range(gain_matrix_array.shape[1]):
    column = gain_matrix_array[:,j]
    print(column)


#first_column=gain_matrix_array[:, 0]
#print (first_column)

[2.38925742e-24 1.17386270e-23 1.03058314e-23 2.78353530e-24]
[9.61831586e-24 6.01437175e-24 1.50899125e-25 1.52411585e-24]
[4.16653032e-23 4.51388756e-23 9.54807222e-24 2.59203274e-25]
[2.22451051e-23 6.73107916e-23 4.03021837e-24 3.17256429e-26]


In [203]:
Result=first_row_random_matrix_array*first_column
print(Result)


[7.36673608e-27 3.23109789e-26 1.91299875e-26 2.18008733e-26]


In [180]:
final = 1+((1 / N_linear)*Result)
print(final)


[1. 1. 1. 1.]


In [184]:
Final_ = np.log2(final)
print(D*Final_)

[-3.65190621e-08 -1.60491668e-07 -9.49815958e-08 -1.08275816e-07]
