In [40]:
#imports
import math
import numpy as np
import random
import itertools
from random import choices
import cmath


In [41]:
#Generating all scenarios in dbm
def generate_all_scenarios(powers, no_of_users):
    combinations = list(itertools.product(powers, repeat=no_of_users))
    return np.array(combinations)


In [42]:
# #Usage
# powers=[0,2,4]
# no_of_users= 4

# result_scenarions_dbm=generate_all_scenarios(powers, no_of_users)
# print(type(result_scenarions_dbm))
# print(result_scenarions_dbm)

In [43]:
def calculate_linear_trans_power(result_scenarions_dbm):
    result=(pow(10, -3) * np.power(10.0, np.array(result_scenarions_dbm, dtype="float") / 10))
    return result


In [44]:
# #Usage
# result_scenarios_linear=calculate_linear_trans_power(result_scenarions_dbm)
# print(type(result_scenarios_linear))
# print(result_scenarios_linear)


In [45]:
#Creating Gain Matrix
import numpy as geek
def channel_matrix(min_distance, max_distance, loss, num_BS_antenna, no_of_users):
    channel_matrix = np.zeros((no_of_users, num_BS_antenna), dtype=complex)
    for i in range(len(channel_matrix)):
        d = random.randint(min_distance, max_distance)  # random distance
        for j in range(len(channel_matrix[0])):
            channel_matrix[i][j] = math.sqrt(pow(d, -loss)) * complex(geek.random.normal(0.0, 1.0), geek.random.normal(0.0, 1.0)) / math.sqrt(2)

    gain_matrix = geek.random.normal(0.0, 0.0, (no_of_users, num_BS_antenna))

    for m in range(len(gain_matrix)):
        for n in range(len(gain_matrix[0])):
            gain_matrix[m][n] = pow(abs(channel_matrix[m][n]), 2)
    return gain_matrix



In [46]:
# # Example usage
# min_distance = 1
# max_distance = 100
# loss = 3
# num_BS_antenna = 4
# num_users = 5

# Gain_matrix=channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users)
# print(Gain_matrix)

In [47]:
#summing columns of gain matrix
def column_sums(Gain_matrix):
    summation_matrix = np.sum(Gain_matrix, axis=0)
    return summation_matrix

In [48]:
# #example usage
# sum_gain = column_sums(Gain_matrix)
# # Printing the result
# print("Column sums of the gain matrix:\n", sum_gain)

In [49]:
# #Converting noise to linear
# D=10**6
# N = -174 + 10 * math.log10(D) #noise in dbm
# linear_noise = calculate_linear_trans_power([N])
# print("Linear noise:", linear_noise)

In [50]:
def calculate_formula_and_sums(result_scenarios_linear, sum_gain, linear_noise):
    a = np.array(result_scenarios_linear)
    b = np.array(sum_gain)
    bit_rate_matrix = (D * np.log2(1 + ((a * b) / linear_noise)))
#     row_sums = np.sum(bit_rate_matrix, axis=1)
    return bit_rate_matrix



In [51]:
#Usage
# bitrate=calculate_formula_and_sums(result_scenarios_linear, sum_gain, linear_noise)
# print(bitrate)

# print("Sum of each row:")
# for i, row_sum in enumerate(row_sums_bitrate):
#     print(f"{row_sum}")
    
# print(row_sums_bitrate)

In [52]:
def row_wise_sums(matrix):
    return [sum(row) for row in matrix]

In [62]:
# # USAGE
# row_sum_bitrate = row_wise_sums(bitrate)
# # print(row_sum_bitrate)
# print(*row_sum_bitrate, sep='\n')

In [54]:
def calculate_average(row_sums_bitrate):
    return np.mean(row_sums_bitrate)


In [55]:
# #usage
# average = calculate_average(row_sum_bitrate)
# print("Average of  Bitrate:", average)

In [56]:
# row_sum_linear_power_scenario = row_wise_sums(result_scenarios_linear)
# print(row_sum_linear_power_scenario)
# # print(*row_sum_linear_scenario, sep='\n')

In [57]:
def find_best_scenario(average, result_scenarions_dbm, result_scenarios_linear, row_sum_bitrate, row_sum_linear_power_scenario):
    best_scenario = None
    best_scenario_index = -1
    min_linear_power = float("inf")

    for i, bitrate in enumerate(row_sum_bitrate):
        if bitrate >= average:
            if row_sum_linear_power_scenario[i] < min_linear_power:
                best_scenario = (result_scenarions_dbm[i], result_scenarios_linear[i], bitrate, row_sum_linear_power_scenario[i])
                best_scenario_index = i
                min_linear_power = row_sum_linear_power_scenario[i]

    return best_scenario_index, best_scenario

# You can change the values here
# average = 20

# result_scenarions_dbm = [
#     [0, 0, 0, 0],
#     [0, 0, 0, 2],
#     [0, 0, 0, 4],
#     [0, 0, 2, 0],
#     [0, 0, 2, 2]
# ]

# result_scenarios_linear = [
#     [0.001     , 0.001     , 0.001     , 0.001     ],
#     [0.001     , 0.001     , 0.001     , 0.00158489],
#     [0.001     , 0.001     , 0.001     , 0.00251189],
#     [0.001     , 0.001     , 0.00158489, 0.001     ],
#     [0.001     , 0.001     , 0.00158489, 0.00158489]
# ]

# row_sum_bitrate = [25, 20, 25, 25, 25]
# row_sum_linear_power_scenario = [10, 2, 3, 1, 20]

# best_scenario_index, best_scenario = find_best_scenario(average, result_scenarions_dbm, result_scenarios_linear, row_sum_bitrate, row_sum_linear_power_scenario)

# print(f"Best scenario index: {best_scenario_index + 1}")
# print(f"dBm matrix row: {best_scenario[0]}")
# print(f"Wattage matrix row: {best_scenario[1]}")
# print(f"row_sum_bitrate: {best_scenario[2]}")
# print(f"row_sum_linear_power_scenario: {best_scenario[3]}")


In [58]:
if __name__ == "__main__":
    
    
    powers=[0,2,4]
    
    
    no_of_users= 4
#    num_users = 4
    
    
    min_distance = 500
    max_distance = 1000
    
    loss = 4
    num_BS_antenna = 4
    
    D=10**6  #bandwidth
    N = -174 + 10 * math.log10(D) #noise in dbm

    #usage for generatig scenarios in dbm
    result_scenarions_dbm=generate_all_scenarios(powers, no_of_users)
    print("scenarios in dbm")
    print(result_scenarions_dbm)
#     print(type(result_scenarions_dbm))
    
    
    #Usage for generating scenarios in watt(linear)
    result_scenarios_linear=calculate_linear_trans_power(result_scenarions_dbm)
    print("Scenarios in watt(linear)")
    print(result_scenarios_linear)
#     print(type(result_scenarios_linear))
    
    
    #usage for creating gain matrix
    print("Gain Matrix")
    Gain_matrix=channel_matrix(min_distance, max_distance, loss, num_BS_antenna, no_of_users)
    print(Gain_matrix)
    
    
    #usage for creating column sum of gain matrix
    sum_gain = column_sums(Gain_matrix)
    print("Column sums of the gain matrix:\n", sum_gain)
    
    
    #usage for converting the noise to linear
    linear_noise = calculate_linear_trans_power([N])
    print("Linear noise:", linear_noise)
    
    
    #Usage for calculating the big fromula
    print("Bitrates")
    bitrate=calculate_formula_and_sums(result_scenarios_linear, sum_gain, linear_noise)
    print(bitrate)
    
    #usage for calucalting the sum of  the rows of bitrates
    print("Sum of the rows of bitrate")
    row_sum_bitrate = row_wise_sums(bitrate)
    print(row_sum_bitrate)
    
       
    
    #usage for calculating the sum of rows of linear scenarios
    print("sum of the rows of linear scenarios")
    row_sum_linear_power_scenario = row_wise_sums(result_scenarios_linear)
    print(row_sum_linear_power_scenario)
    
    #usage for calculating the average
    average = calculate_average(row_sum_bitrate)
    print("Average of  Bitrate:", average)
    
    
    #usage for calucalting the best scenarios that satisifies the user requirement
    best_scenario_index, best_scenario = find_best_scenario(average, result_scenarions_dbm, result_scenarios_linear, row_sum_bitrate, row_sum_linear_power_scenario)
    print(f"Best scenario index: {best_scenario_index + 1}")
    print(f"dBm matrix row: {best_scenario[0]}")
    print(f"Wattage matrix row: {best_scenario[1]}")
    print(f"row_sum_bitrate: {best_scenario[2]}")
    print(f"row_sum_linear_power_scenario: {best_scenario[3]}")
    
    
    
    
    

scenarios in dbm
[[0 0 0 0]
 [0 0 0 2]
 [0 0 0 4]
 [0 0 2 0]
 [0 0 2 2]
 [0 0 2 4]
 [0 0 4 0]
 [0 0 4 2]
 [0 0 4 4]
 [0 2 0 0]
 [0 2 0 2]
 [0 2 0 4]
 [0 2 2 0]
 [0 2 2 2]
 [0 2 2 4]
 [0 2 4 0]
 [0 2 4 2]
 [0 2 4 4]
 [0 4 0 0]
 [0 4 0 2]
 [0 4 0 4]
 [0 4 2 0]
 [0 4 2 2]
 [0 4 2 4]
 [0 4 4 0]
 [0 4 4 2]
 [0 4 4 4]
 [2 0 0 0]
 [2 0 0 2]
 [2 0 0 4]
 [2 0 2 0]
 [2 0 2 2]
 [2 0 2 4]
 [2 0 4 0]
 [2 0 4 2]
 [2 0 4 4]
 [2 2 0 0]
 [2 2 0 2]
 [2 2 0 4]
 [2 2 2 0]
 [2 2 2 2]
 [2 2 2 4]
 [2 2 4 0]
 [2 2 4 2]
 [2 2 4 4]
 [2 4 0 0]
 [2 4 0 2]
 [2 4 0 4]
 [2 4 2 0]
 [2 4 2 2]
 [2 4 2 4]
 [2 4 4 0]
 [2 4 4 2]
 [2 4 4 4]
 [4 0 0 0]
 [4 0 0 2]
 [4 0 0 4]
 [4 0 2 0]
 [4 0 2 2]
 [4 0 2 4]
 [4 0 4 0]
 [4 0 4 2]
 [4 0 4 4]
 [4 2 0 0]
 [4 2 0 2]
 [4 2 0 4]
 [4 2 2 0]
 [4 2 2 2]
 [4 2 2 4]
 [4 2 4 0]
 [4 2 4 2]
 [4 2 4 4]
 [4 4 0 0]
 [4 4 0 2]
 [4 4 0 4]
 [4 4 2 0]
 [4 4 2 2]
 [4 4 2 4]
 [4 4 4 0]
 [4 4 4 2]
 [4 4 4 4]]
Scenarios in watt(linear)
[[0.001      0.001      0.001      0.001     ]
 [0.001      0.001

In [66]:
for i, (x, y, z, a) in enumerate(zip(row_sum_linear_power_scenario, row_sum_bitrate, result_scenarions_dbm, result_scenarios_linear)):
    print(i, x, y, z, a, sep='      ')

0      0.004      10793077.253094662      [0 0 0 0]      [0.001 0.001 0.001 0.001]
1      0.0045848931924611135      11365408.221379425      [0 0 0 2]      [0.001      0.001      0.001      0.00158489]
2      0.00551188643150958      11968535.866087597      [0 0 0 4]      [0.001      0.001      0.001      0.00251189]
3      0.0045848931924611135      11391819.668626651      [0 0 2 0]      [0.001      0.001      0.00158489 0.001     ]
4      0.005169786384922227      11964150.636911415      [0 0 2 2]      [0.001      0.001      0.00158489 0.00158489]
5      0.006096779623970694      12567278.281619586      [0 0 2 4]      [0.001      0.001      0.00158489 0.00251189]
6      0.00551188643150958      12013195.72582271      [0 0 4 0]      [0.001      0.001      0.00251189 0.001     ]
7      0.006096779623970694      12585526.694107475      [0 0 4 2]      [0.001      0.001      0.00251189 0.00158489]
8      0.007023772863019161      13188654.338815646      [0 0 4 4]      [0.001      0.001   