In [11]:
#imports
import math
import numpy as np
import random
import itertools

In [12]:
#constants
D=10**6  #Bandwodth
N= -174+10*(math.log10(D))  #Noise in DBM
N_linear=(N)*(10**(-3))*(10**(N/10))    #Noise in miliwatt


In [13]:
# Compute the linear power of the population
# Takes a list of population values and returns an array of corresponding linear transmission power values IN WATTS.
import numpy as np
def calculate_linear_trans_power(population):
    return pow(10,-3)*np.power(10.0,np.array(population, dtype="float")/10)

In [14]:
population = [0, 2, 4]
linear_power_values=calculate_linear_trans_power(population)
rounded_values = np.round(linear_power_values, 5)
print(rounded_values)

[0.001   0.00158 0.00251]


In [15]:
#Scenarios in dbm
def generate_combinations(powers, num_of_users):
    combinations = list(itertools.product(powers, repeat=num_of_users))

    for index, combination in enumerate(combinations, start=1):
        print(f"{index}. {combination}")

# Example usage
powers = [0, 2, 4]
num_of_users = 4
scenarios=generate_combinations(powers, num_of_users)

1. (0, 0, 0, 0)
2. (0, 0, 0, 2)
3. (0, 0, 0, 4)
4. (0, 0, 2, 0)
5. (0, 0, 2, 2)
6. (0, 0, 2, 4)
7. (0, 0, 4, 0)
8. (0, 0, 4, 2)
9. (0, 0, 4, 4)
10. (0, 2, 0, 0)
11. (0, 2, 0, 2)
12. (0, 2, 0, 4)
13. (0, 2, 2, 0)
14. (0, 2, 2, 2)
15. (0, 2, 2, 4)
16. (0, 2, 4, 0)
17. (0, 2, 4, 2)
18. (0, 2, 4, 4)
19. (0, 4, 0, 0)
20. (0, 4, 0, 2)
21. (0, 4, 0, 4)
22. (0, 4, 2, 0)
23. (0, 4, 2, 2)
24. (0, 4, 2, 4)
25. (0, 4, 4, 0)
26. (0, 4, 4, 2)
27. (0, 4, 4, 4)
28. (2, 0, 0, 0)
29. (2, 0, 0, 2)
30. (2, 0, 0, 4)
31. (2, 0, 2, 0)
32. (2, 0, 2, 2)
33. (2, 0, 2, 4)
34. (2, 0, 4, 0)
35. (2, 0, 4, 2)
36. (2, 0, 4, 4)
37. (2, 2, 0, 0)
38. (2, 2, 0, 2)
39. (2, 2, 0, 4)
40. (2, 2, 2, 0)
41. (2, 2, 2, 2)
42. (2, 2, 2, 4)
43. (2, 2, 4, 0)
44. (2, 2, 4, 2)
45. (2, 2, 4, 4)
46. (2, 4, 0, 0)
47. (2, 4, 0, 2)
48. (2, 4, 0, 4)
49. (2, 4, 2, 0)
50. (2, 4, 2, 2)
51. (2, 4, 2, 4)
52. (2, 4, 4, 0)
53. (2, 4, 4, 2)
54. (2, 4, 4, 4)
55. (4, 0, 0, 0)
56. (4, 0, 0, 2)
57. (4, 0, 0, 4)
58. (4, 0, 2, 0)
59. (4, 0, 2, 2)
60. (4

In [24]:
import itertools
import numpy as np

def print_linear_power_values(scenarios):
    for index, scenario in enumerate(scenarios, start=1):
        linear_power_values = calculate_linear_trans_power(scenario)
        print(f"{index} => {linear_power_values}")

#Example usage
print_linear_power_values(scenarios)


1 => [0.001 0.001 0.001 0.001]
2 => [0.001      0.001      0.001      0.00158489]
3 => [0.001      0.001      0.001      0.00251189]
4 => [0.001      0.001      0.00158489 0.001     ]
5 => [0.001      0.001      0.00158489 0.00158489]
6 => [0.001      0.001      0.00158489 0.00251189]
7 => [0.001      0.001      0.00251189 0.001     ]
8 => [0.001      0.001      0.00251189 0.00158489]
9 => [0.001      0.001      0.00251189 0.00251189]
10 => [0.001      0.00158489 0.001      0.001     ]
11 => [0.001      0.00158489 0.001      0.00158489]
12 => [0.001      0.00158489 0.001      0.00251189]
13 => [0.001      0.00158489 0.00158489 0.001     ]
14 => [0.001      0.00158489 0.00158489 0.00158489]
15 => [0.001      0.00158489 0.00158489 0.00251189]
16 => [0.001      0.00158489 0.00251189 0.001     ]
17 => [0.001      0.00158489 0.00251189 0.00158489]
18 => [0.001      0.00158489 0.00251189 0.00251189]
19 => [0.001      0.00251189 0.001      0.001     ]
20 => [0.001      0.00251189 0.001      0

In [8]:
#Creating Gain Matrix
def channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users):
    channel_matrix = np.zeros((num_users, num_BS_antenna), dtype=complex)
    
    for i in range(num_users):
        d = random.randint(min_distance, max_distance)  # random distance
        path_loss_factor = d ** (-loss)
        
        for j in range(num_BS_antenna):
            channel_coefficient = path_loss_factor * (np.random.randn() + 1j * np.random.randn()) / np.sqrt(2)
            channel_matrix[i][j] = channel_coefficient
            
    gain_matrix = np.abs(channel_matrix) ** 2
    return channel_matrix, gain_matrix

# Example usage
min_distance = 500
max_distance = 1000
loss = 4
num_BS_antenna = 4
num_users = 4

channel_mat, gain_matrix = channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users)

channel_mat_array=np.array(channel_mat)  #Printing chaneel Matrix
print("Channel matrix:\n", channel_mat_array)   #converting the matrix to array

gain_matrix_array=np.array(gain_matrix)   #Printing Gain Matrix
print("Gain matrix:\n", gain_matrix_array)     #converting the matrix to array


Channel matrix:
 [[-2.64970265e-14-1.85953205e-12j  3.27269958e-13-4.36045400e-13j
   1.52400916e-12+1.82484648e-12j -8.10910817e-13-1.56205421e-12j]
 [ 5.50107698e-13-8.22426229e-13j -8.98396650e-13+8.80817705e-13j
  -6.52512177e-14-5.46463819e-14j  7.15214768e-14+4.15542417e-13j]
 [ 1.13942903e-12-2.98220936e-12j -1.40544017e-12+4.76559290e-12j
  -1.96769421e-12+4.29371485e-12j -1.94982008e-12+1.49134550e-12j]
 [-9.96997082e-14+3.17814788e-13j  3.69252880e-13+8.03557438e-13j
  -1.40466778e-12+1.21531637e-12j  6.25949720e-13+2.21741026e-13j]]
Gain matrix:
 [[3.45856153e-24 2.97241217e-25 5.65266859e-24 3.09758971e-24]
 [9.79003382e-25 1.58295637e-24 7.24394846e-27 1.77790822e-25]
 [1.01918712e-23 2.46861378e-23 2.23078077e-23 6.02590977e-24]
 [1.10946271e-25 7.82052245e-25 3.45008547e-24 4.40982134e-25]]


In [ ]:
first_row_random_matrix_array = random_matrix_array[0][0]
print (first_row_random_matrix_array)


In [ ]:
for j in range(gain_matrix_array.shape[1]):
    column = gain_matrix_array[:,j]
    print(column)


first_column=gain_matrix_array[:, 0]
print (first_column)

In [ ]:
Result=first_row_random_matrix_array*first_column
print(Result)


In [ ]:
final = 1+((1 / N_linear)*Result)
print(final)


In [ ]:
Final_ = np.log2(final)
print(D*Final_)

In [ ]:
# Function to multiply a row with corresponding columns
def multiply_row_with_columns(row, matrix):
    results = []
    for i, element in enumerate(row):
        column = [row[i] for row in matrix]
        result = [element * col_element for col_element in column]
        results.append(result)
    return results

# Define the row indices you want to use for the multiplication
row_indices = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,
               40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
               50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
               60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
               70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]  # You can extend this list to include more row indices

# Initialize an empty list to store the results
all_results = []

# Multiply each element of the specified rows with the corresponding columns
for row_idx in row_indices:
    row = random_matrix_array[row_idx]
    results = multiply_row_with_columns(row, gain_matrix_array)
    all_results.append(results)

# Print the results
for idx, results in enumerate(all_results):
    row_idx = row_indices[idx]
    print(f"Results for row {row_idx + 1}:")
    for i, result in enumerate(results):
        print(f"  Element {i + 1} of the row multiplied with the corresponding column:")
        print(f"  {result}")
    print()


In [ ]:
for idx, results in enumerate(all_results):
    row_idx = row_indices[idx]
    print(f"Results for row {row_idx + 1}:")
    for i, result in enumerate(results):
        Final_Result= [D*(math.log2((1+(1/N_linear)*value))) for value in result]
        print(f"  Element {i + 1} of the row multiplied with the corresponding column:")
        print(f"  {Final_Result}")  # Add 2 to each element when printing
    print()

In [ ]:
# Function to sum the resulting matrices for a specific row
def sum_resulting_matrices(row_idx, all_results):
    return np.sum(all_results[row_idx], axis=0)

# Perform addition on many resulting matrices
for row_idx in row_indices:
    sum_result = sum_resulting_matrices(row_idx, all_results)
    print(f"Sum of the resulting matrices for row {row_idx + 1}: {sum_result}")