In [1]:
#imports
import math
import numpy as np
import random
import itertools
from random import choices
import cmath


In [2]:
#Generating all scenarios in dbm
def generate_all_scenarios(powers, no_of_users):
    combinations = list(itertools.product(powers, repeat=no_of_users))
    return np.array(combinations)


In [3]:
#Usage
powers=[0,2,4]
no_of_users= 4

result_scenarions_dbm=generate_all_scenarios(powers, no_of_users)
print(type(result_scenarions_dbm))
print(result_scenarions_dbm)

<class 'numpy.ndarray'>
[[0 0 0 0]
 [0 0 0 2]
 [0 0 0 4]
 [0 0 2 0]
 [0 0 2 2]
 [0 0 2 4]
 [0 0 4 0]
 [0 0 4 2]
 [0 0 4 4]
 [0 2 0 0]
 [0 2 0 2]
 [0 2 0 4]
 [0 2 2 0]
 [0 2 2 2]
 [0 2 2 4]
 [0 2 4 0]
 [0 2 4 2]
 [0 2 4 4]
 [0 4 0 0]
 [0 4 0 2]
 [0 4 0 4]
 [0 4 2 0]
 [0 4 2 2]
 [0 4 2 4]
 [0 4 4 0]
 [0 4 4 2]
 [0 4 4 4]
 [2 0 0 0]
 [2 0 0 2]
 [2 0 0 4]
 [2 0 2 0]
 [2 0 2 2]
 [2 0 2 4]
 [2 0 4 0]
 [2 0 4 2]
 [2 0 4 4]
 [2 2 0 0]
 [2 2 0 2]
 [2 2 0 4]
 [2 2 2 0]
 [2 2 2 2]
 [2 2 2 4]
 [2 2 4 0]
 [2 2 4 2]
 [2 2 4 4]
 [2 4 0 0]
 [2 4 0 2]
 [2 4 0 4]
 [2 4 2 0]
 [2 4 2 2]
 [2 4 2 4]
 [2 4 4 0]
 [2 4 4 2]
 [2 4 4 4]
 [4 0 0 0]
 [4 0 0 2]
 [4 0 0 4]
 [4 0 2 0]
 [4 0 2 2]
 [4 0 2 4]
 [4 0 4 0]
 [4 0 4 2]
 [4 0 4 4]
 [4 2 0 0]
 [4 2 0 2]
 [4 2 0 4]
 [4 2 2 0]
 [4 2 2 2]
 [4 2 2 4]
 [4 2 4 0]
 [4 2 4 2]
 [4 2 4 4]
 [4 4 0 0]
 [4 4 0 2]
 [4 4 0 4]
 [4 4 2 0]
 [4 4 2 2]
 [4 4 2 4]
 [4 4 4 0]
 [4 4 4 2]
 [4 4 4 4]]


In [7]:
def calculate_linear_trans_power(result_scenarions_dbm):
    result=(pow(10, -3) * np.power(10.0, np.array(result_scenarions_dbm, dtype="float") / 10))
    return result


In [8]:
#Usage
result_scenarios_linear=calculate_linear_trans_power(result_scenarions_dbm)
print(type(result_scenarios_linear))
print(result_scenarios_linear)


<class 'numpy.ndarray'>
[[0.001      0.001      0.001      0.001     ]
 [0.001      0.001      0.001      0.00158489]
 [0.001      0.001      0.001      0.00251189]
 [0.001      0.001      0.00158489 0.001     ]
 [0.001      0.001      0.00158489 0.00158489]
 [0.001      0.001      0.00158489 0.00251189]
 [0.001      0.001      0.00251189 0.001     ]
 [0.001      0.001      0.00251189 0.00158489]
 [0.001      0.001      0.00251189 0.00251189]
 [0.001      0.00158489 0.001      0.001     ]
 [0.001      0.00158489 0.001      0.00158489]
 [0.001      0.00158489 0.001      0.00251189]
 [0.001      0.00158489 0.00158489 0.001     ]
 [0.001      0.00158489 0.00158489 0.00158489]
 [0.001      0.00158489 0.00158489 0.00251189]
 [0.001      0.00158489 0.00251189 0.001     ]
 [0.001      0.00158489 0.00251189 0.00158489]
 [0.001      0.00158489 0.00251189 0.00251189]
 [0.001      0.00251189 0.001      0.001     ]
 [0.001      0.00251189 0.001      0.00158489]
 [0.001      0.00251189 0.001      0

In [14]:
#Creating Gain Matrix
import numpy as geek
def channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users):
    channel_matrix = np.zeros((num_users, num_BS_antenna), dtype=complex)
    for i in range(len(channel_matrix)):
        d = random.randint(min_distance, max_distance)  # random distance
        for j in range(len(channel_matrix[0])):
            channel_matrix[i][j] = math.sqrt(pow(d, -loss)) * complex(geek.random.normal(0.0, 1.0), geek.random.normal(0.0, 1.0)) / math.sqrt(2)

    gain_matrix = geek.random.normal(0.0, 0.0, (num_users, num_BS_antenna))

    for m in range(len(gain_matrix)):
        for n in range(len(gain_matrix[0])):
            gain_matrix[m][n] = pow(abs(channel_matrix[m][n]), 2)
    return gain_matrix



In [15]:
# Example usage
min_distance = 1
max_distance = 100
loss = 3
num_BS_antenna = 4
num_users = 5

Gain_matrix=channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users)
print(Gain_matrix)

[[6.82295009e-01 8.20151041e-01 2.95217279e-01 1.27238638e+00]
 [1.77414623e-04 8.90527796e-05 1.92262191e-06 2.72259091e-05]
 [1.10038584e-06 4.43180673e-07 2.76906884e-06 1.60768953e-06]
 [4.86874676e-04 6.15279673e-05 9.82926394e-05 1.55451429e-04]
 [1.18466234e-05 5.17021040e-05 2.25816243e-06 6.19833827e-05]]


In [19]:
#summing columns of gain matrix
def column_sums(Gain_matrix):
    summation_matrix = np.sum(Gain_matrix, axis=0)
    return summation_matrix

In [20]:
#example usage
sum_gain = column_sums(Gain_matrix)
# Printing the result
print("Column sums of the gain matrix:\n", sum_gain)

Column sums of the gain matrix:
 [0.68297225 0.82035377 0.29532252 1.27263265]


In [38]:
def calculate_linear_trans_power(population): # converting noise to watt
    return pow(10, -3) * np.power(10.0, np.array(population, dtype="float") / 10)

In [42]:
#usage
D=10**6
N = -174 + 10 * math.log10(D) #noise in dbm
linear_noise = calculate_linear_trans_power([N])
print("Linear noise:", linear_noise)

Linear noise: [3.98107171e-15]


In [51]:
def calculate_row_sums(result_scenarios_linear, sum_gain, linear_noise):
    a = np.array(result_scenarios_linear)
    b = np.array(sum_gain)
    bit_rate_matrix = (D * np.log2(1 + ((a * b) / linear_noise)))
    row_sums = np.sum(bit_rate_matrix, axis=1)
    return row_sums

def print_row_sums(row_sums):
    print("Sum of each row:")
    for i, row_sum in enumerate(row_sums):
        print(f"{row_sum}")
        
# print(bit_rate_matrix)

In [47]:
print_row_sums(row_sums)

Sum of each row:
149232317.40425393
149896703.02322975
150561088.64220616
149896703.02322423
150561088.64220005
151225474.26117647
150561088.64219716
151225474.26117298
151889859.8801494
149896703.02322882
150561088.64220464
151225474.26118106
150561088.64219913
151225474.26117495
151889859.88015136
151225474.26117206
151889859.88014787
152554245.4991243
150561088.64220467
151225474.2611805
151889859.8801569
151225474.26117498
151889859.8801508
152554245.4991272
151889859.8801479
152554245.49912372
153218631.11810014
149896703.02322832
150561088.64220414
151225474.26118055
150561088.64219862
151225474.26117444
151889859.88015085
151225474.26117155
151889859.88014737
152554245.49912378
150561088.6422032
151225474.26117903
151889859.88015544
151225474.26117352
151889859.88014933
152554245.49912575
151889859.88014644
152554245.49912226
153218631.11809868
151225474.26117906
151889859.88015485
152554245.4991313
151889859.88014933
152554245.49912515
153218631.11810157
152554245.4991223
15321

In [54]:
def calculate_average(row_sums):
    return np.mean(row_sums)
average = calculate_average(row_sums)
print("Average of row sums:", average)

Average of row sums: 151889859.8801511


In [ ]:
def constrained_optimization_algorithm(scenarios_in_linear, total_bitrate,average_sum  ):
    

In [ ]:
scenarios = [
        [0.001, 0.001, 0.001, 0.001],
        [0.001, 0.001, 0.001, 0.00158489],
        [0.001, 0.001, 0.001, 0.00251189],
        [0.001, 0.001, 0.00158489, 0.001],
        [0.001, 0.001, 0.00158489, 0.00158489],
        [0.001, 0.001, 0.00158489, 0.00251189]
    ]
row_sums = [
    [0.004],
    [0.00458489],
    [0.00551189],
    [0.00458489],
    [0.00516878],
    [0.00609578]
]

total_bitrate_matrix = [
    [4000000.0001460826],
    [4000000.0001848647],
    [4000000.0002463306],
    [4000000.000159239],
    [4000000.000198021],
    [4000000.000259487]
]

average_bitrate = 4000000.0001996185


# Initialize lowest_bitrate to be infinity
lowest_bitrate = float('inf')

# Iterate over the row_sums and total_bitrate_matrix simultaneously
for i, (row_sum, total_bitrate) in enumerate(zip(row_sums, total_bitrate_matrix)):
    # Check if the total bitrate is greater than or equal to the average bitrate
    if total_bitrate[0] >= average_bitrate:
        # Check if the row sum is less than the current lowest bitrate
        if row_sum[0] < lowest_bitrate:
            # Update the lowest bitrate, lowest bitrate scenario, and lowest bitrate scenario's power values
            lowest_bitrate = row_sum[0]
            lowest_bitrate_scenario = i+1
            lowest_bitrate_scenario_powers = scenarios[i]

# Print the lowest bitrate scenario, bitrate, and the power values used to obtain the lowest bitrate
if lowest_bitrate_scenario:
    print(f"Lowest possible bitrate scenario: {lowest_bitrate_scenario}")
    print(f"Lowest possible bitrate: {lowest_bitrate}")
    print(f"Power values used for the lowest bitrate scenario: {lowest_bitrate_scenario_powers}")
else:
    print("No scenario achieves a total bitrate greater than or equal to the average bitrate.")
