In [30]:
#imports
import math
import numpy as np
import random

In [31]:
#constants
D=10**6  #Bandwodth
N= -174+10*(math.log10(D))  #Noise in DBM
N_linear=(N)*(10**(-3))*(10**(N/10))    #Noise in miliwatt


In [33]:
#converting Powers {0,2,4}dbm to watt  rounded to 4 decimal palce
watt1 =round(10 ** (0 / 10) * 0.001, 4) 
watt2 = round(10 ** (2 / 10) * 0.001, 4)
watt3 = round(10 ** (4 / 10) * 0.001,4)
mylist=[watt1,watt2,watt3]
print(mylist)


[0.001, 0.0016, 0.0025]


In [14]:
#creating scenarios in watt
n=1
def create_random_matrix(rows, columns):
    matrix = [[random.choice(mylist) for _ in range(columns)] for _ in range(rows)]
    return matrix
rows = 81
columns = 4
random_matrix = create_random_matrix(rows, columns)  #the matrix

random_matrix_array=np.array(random_matrix)  #converting the matrix to array
print(random_matrix_array)





[[0.001  0.0016 0.0016 0.0025]
 [0.001  0.0016 0.001  0.0025]
 [0.0016 0.0016 0.001  0.0016]
 [0.001  0.001  0.001  0.0016]
 [0.0016 0.0025 0.001  0.0025]
 [0.0025 0.0016 0.0016 0.0016]
 [0.0025 0.0025 0.0025 0.0016]
 [0.0025 0.0025 0.0025 0.001 ]
 [0.0025 0.001  0.0025 0.001 ]
 [0.001  0.001  0.0016 0.001 ]
 [0.0025 0.0016 0.0016 0.0025]
 [0.0016 0.0025 0.0016 0.0025]
 [0.001  0.0025 0.0016 0.0025]
 [0.001  0.0016 0.0025 0.001 ]
 [0.001  0.001  0.001  0.0025]
 [0.0016 0.0025 0.001  0.0025]
 [0.0025 0.0025 0.0025 0.0025]
 [0.0016 0.001  0.0016 0.0016]
 [0.0016 0.0025 0.0025 0.001 ]
 [0.001  0.0016 0.0025 0.001 ]
 [0.001  0.0025 0.001  0.0025]
 [0.0025 0.0025 0.001  0.001 ]
 [0.0025 0.0025 0.0016 0.0016]
 [0.0016 0.0016 0.0016 0.0016]
 [0.0016 0.001  0.0016 0.0016]
 [0.001  0.0025 0.0025 0.0025]
 [0.0025 0.0016 0.001  0.0016]
 [0.001  0.0025 0.0016 0.0025]
 [0.001  0.0025 0.0016 0.0016]
 [0.0025 0.001  0.001  0.0016]
 [0.0025 0.001  0.0016 0.0025]
 [0.001  0.0016 0.0025 0.0025]
 [0.001 

In [15]:
def channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users):
    channel_matrix = np.zeros((num_users, num_BS_antenna), dtype=complex)
    
    for i in range(num_users):
        d = random.randint(min_distance, max_distance)  # random distance
        path_loss_factor = d ** (-loss)
        
        for j in range(num_BS_antenna):
            channel_coefficient = path_loss_factor * (np.random.randn() + 1j * np.random.randn()) / np.sqrt(2)
            channel_matrix[i][j] = channel_coefficient
            
    gain_matrix = np.abs(channel_matrix) ** 2
    return channel_matrix, gain_matrix

# Example usage
min_distance = 500
max_distance = 1000
loss = 4
num_BS_antenna = 4
num_users = 4

channel_mat, gain_matrix = channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users)

channel_mat_array=np.array(channel_mat)  #matrix
print("Channel matrix:\n", channel_mat_array)   #converting the matrix to array

gain_matrix_array=np.array(gain_matrix)   #matrix
print("Gain matrix:\n", gain_matrix_array)     #converting the matrix to array





Channel matrix:
 [[ 1.93587406e-12-1.10534462e-12j  2.63766067e-12+1.37692943e-12j
  -3.11776696e-12-2.16149116e-13j  4.94883582e-12-7.49478439e-13j]
 [-2.80985367e-12-3.21998745e-12j -2.73997926e-12-4.37887594e-13j
  -6.92111457e-13+3.70390640e-12j -4.50199661e-14+3.02529521e-13j]
 [ 3.52899247e-13+1.40995094e-12j  4.70770536e-13-1.63694496e-13j
  -1.07204910e-12-1.70672220e-13j -7.99490371e-13+1.47287708e-12j]
 [-2.04928039e-12-2.77225838e-12j  1.05009095e-11-5.80003255e-12j
  -4.07717805e-12-6.15404125e-12j  2.80864385e-12+1.07513234e-11j]]
Gain matrix:
 [[4.96939511e-24 8.85318850e-24 9.76719124e-24 2.50526939e-23]
 [1.82635968e-23 7.69923190e-24 1.41979409e-23 9.35509085e-26]
 [2.11249953e-24 2.48420786e-25 1.17841827e-24 2.80855174e-24]
 [1.18849666e-23 1.43909479e-22 5.44956046e-23 1.23479435e-22]]


In [16]:
first_row_random_matrix_array = random_matrix_array[0][0]
print (first_row_random_matrix_array)


0.001


In [36]:
for j in range(gain_matrix_array.shape[1]):
    column = gain_matrix_array[:,j]
    print(column)


first_column=gain_matrix_array[:, 0]
print (first_column)

[4.96939511e-24 1.82635968e-23 2.11249953e-24 1.18849666e-23]
[8.85318850e-24 7.69923190e-24 2.48420786e-25 1.43909479e-22]
[9.76719124e-24 1.41979409e-23 1.17841827e-24 5.44956046e-23]
[2.50526939e-23 9.35509085e-26 2.80855174e-24 1.23479435e-22]
[4.96939511e-24 1.82635968e-23 2.11249953e-24 1.18849666e-23]


In [37]:
Result=first_row_random_matrix_array*first_column
print(Result)


[4.96939511e-27 1.82635968e-26 2.11249953e-27 1.18849666e-26]


In [38]:
final = 1+((1 / N_linear)*Result)
print(final)


[1. 1. 1. 1.]


In [39]:
Final_ = np.log2(final)
print(D*Final_)

[-1.58569612e-08 -5.79820197e-08 -6.72719566e-09 -3.78004327e-08]


In [49]:
# Function to multiply a row with corresponding columns
def multiply_row_with_columns(row, matrix):
    results = []
    for i, element in enumerate(row):
        column = [row[i] for row in matrix]
        result = [element * col_element for col_element in column]
        results.append(result)
    return results

# Define the row indices you want to use for the multiplication
row_indices = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,
               40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
               50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
               60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
               70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]  # You can extend this list to include more row indices

# Initialize an empty list to store the results
all_results = []

# Multiply each element of the specified rows with the corresponding columns
for row_idx in row_indices:
    row = random_matrix_array[row_idx]
    results = multiply_row_with_columns(row, gain_matrix_array)
    all_results.append(results)

# Print the results
for idx, results in enumerate(all_results):
    row_idx = row_indices[idx]
    print(f"Results for row {row_idx + 1}:")
    for i, result in enumerate(results):
        print(f"  Element {i + 1} of the row multiplied with the corresponding column:")
        print(f"  {result}")
    print()


Results for row 1:
  Element 1 of the row multiplied with the corresponding column:
  [4.96939511377455e-27, 1.8263596821873964e-26, 2.112499529952411e-27, 1.1884966637671144e-26]
  Element 2 of the row multiplied with the corresponding column:
  [1.4165101604302145e-26, 1.2318771044913275e-26, 3.9747325736146445e-28, 2.302551656355551e-25]
  Element 3 of the row multiplied with the corresponding column:
  [1.5627505987261523e-26, 2.271670540448745e-26, 1.8854692313040363e-27, 8.719296739458958e-26]
  Element 4 of the row multiplied with the corresponding column:
  [6.26317346495365e-26, 2.3387727116065444e-28, 7.021379361059592e-27, 3.0869858779034387e-25]

Results for row 2:
  Element 1 of the row multiplied with the corresponding column:
  [4.96939511377455e-27, 1.8263596821873964e-26, 2.112499529952411e-27, 1.1884966637671144e-26]
  Element 2 of the row multiplied with the corresponding column:
  [1.4165101604302145e-26, 1.2318771044913275e-26, 3.9747325736146445e-28, 2.30255165635