In [62]:
#imports
import math
import numpy as np
import random
import itertools
from random import choices
import cmath


In [63]:
#Generating all scenarios in dbm
def generate_all_scenarios(powers, no_of_users):
    combinations = list(itertools.product(powers, repeat=no_of_users))
    return np.array(combinations)


In [64]:
#Usage
powers=[0,2,4]
no_of_users= 4

result_scenarions_dbm=generate_all_scenarios(powers, no_of_users)
print(type(result_scenarions_dbm))
print(result_scenarions_dbm)

<class 'numpy.ndarray'>
[[0 0 0 0]
 [0 0 0 2]
 [0 0 0 4]
 [0 0 2 0]
 [0 0 2 2]
 [0 0 2 4]
 [0 0 4 0]
 [0 0 4 2]
 [0 0 4 4]
 [0 2 0 0]
 [0 2 0 2]
 [0 2 0 4]
 [0 2 2 0]
 [0 2 2 2]
 [0 2 2 4]
 [0 2 4 0]
 [0 2 4 2]
 [0 2 4 4]
 [0 4 0 0]
 [0 4 0 2]
 [0 4 0 4]
 [0 4 2 0]
 [0 4 2 2]
 [0 4 2 4]
 [0 4 4 0]
 [0 4 4 2]
 [0 4 4 4]
 [2 0 0 0]
 [2 0 0 2]
 [2 0 0 4]
 [2 0 2 0]
 [2 0 2 2]
 [2 0 2 4]
 [2 0 4 0]
 [2 0 4 2]
 [2 0 4 4]
 [2 2 0 0]
 [2 2 0 2]
 [2 2 0 4]
 [2 2 2 0]
 [2 2 2 2]
 [2 2 2 4]
 [2 2 4 0]
 [2 2 4 2]
 [2 2 4 4]
 [2 4 0 0]
 [2 4 0 2]
 [2 4 0 4]
 [2 4 2 0]
 [2 4 2 2]
 [2 4 2 4]
 [2 4 4 0]
 [2 4 4 2]
 [2 4 4 4]
 [4 0 0 0]
 [4 0 0 2]
 [4 0 0 4]
 [4 0 2 0]
 [4 0 2 2]
 [4 0 2 4]
 [4 0 4 0]
 [4 0 4 2]
 [4 0 4 4]
 [4 2 0 0]
 [4 2 0 2]
 [4 2 0 4]
 [4 2 2 0]
 [4 2 2 2]
 [4 2 2 4]
 [4 2 4 0]
 [4 2 4 2]
 [4 2 4 4]
 [4 4 0 0]
 [4 4 0 2]
 [4 4 0 4]
 [4 4 2 0]
 [4 4 2 2]
 [4 4 2 4]
 [4 4 4 0]
 [4 4 4 2]
 [4 4 4 4]]


In [65]:
def calculate_linear_trans_power(result_scenarions_dbm):
    result=(pow(10, -3) * np.power(10.0, np.array(result_scenarions_dbm, dtype="float") / 10))
    return result


In [66]:
#Usage
result_scenarios_linear=calculate_linear_trans_power(result_scenarions_dbm)
print(type(result_scenarios_linear))
print(result_scenarios_linear)


<class 'numpy.ndarray'>
[[0.001      0.001      0.001      0.001     ]
 [0.001      0.001      0.001      0.00158489]
 [0.001      0.001      0.001      0.00251189]
 [0.001      0.001      0.00158489 0.001     ]
 [0.001      0.001      0.00158489 0.00158489]
 [0.001      0.001      0.00158489 0.00251189]
 [0.001      0.001      0.00251189 0.001     ]
 [0.001      0.001      0.00251189 0.00158489]
 [0.001      0.001      0.00251189 0.00251189]
 [0.001      0.00158489 0.001      0.001     ]
 [0.001      0.00158489 0.001      0.00158489]
 [0.001      0.00158489 0.001      0.00251189]
 [0.001      0.00158489 0.00158489 0.001     ]
 [0.001      0.00158489 0.00158489 0.00158489]
 [0.001      0.00158489 0.00158489 0.00251189]
 [0.001      0.00158489 0.00251189 0.001     ]
 [0.001      0.00158489 0.00251189 0.00158489]
 [0.001      0.00158489 0.00251189 0.00251189]
 [0.001      0.00251189 0.001      0.001     ]
 [0.001      0.00251189 0.001      0.00158489]
 [0.001      0.00251189 0.001      0

In [67]:
#Creating Gain Matrix
import numpy as geek
def channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users):
    channel_matrix = np.zeros((num_users, num_BS_antenna), dtype=complex)
    for i in range(len(channel_matrix)):
        d = random.randint(min_distance, max_distance)  # random distance
        for j in range(len(channel_matrix[0])):
            channel_matrix[i][j] = math.sqrt(pow(d, -loss)) * complex(geek.random.normal(0.0, 1.0), geek.random.normal(0.0, 1.0)) / math.sqrt(2)

    gain_matrix = geek.random.normal(0.0, 0.0, (num_users, num_BS_antenna))

    for m in range(len(gain_matrix)):
        for n in range(len(gain_matrix[0])):
            gain_matrix[m][n] = pow(abs(channel_matrix[m][n]), 2)
    return gain_matrix



In [68]:
# Example usage
min_distance = 1
max_distance = 100
loss = 3
num_BS_antenna = 4
num_users = 5

Gain_matrix=channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users)
print(Gain_matrix)

[[3.14115907e-05 9.24728249e-06 1.42613038e-05 4.00256940e-06]
 [2.39028467e-04 7.65757161e-09 5.06313977e-06 8.88987196e-06]
 [3.65130474e-06 3.05768882e-07 3.18902415e-06 1.21415737e-06]
 [3.59372316e-05 1.59932107e-05 6.42705806e-05 5.05616924e-05]
 [1.03460299e-06 3.07428516e-06 6.78612010e-06 1.77296770e-06]]


In [105]:
#summing columns of gain matrix
def column_sums(Gain_matrix):
    summation_matrix = np.sum(Gain_matrix, axis=0)
    return summation_matrix

In [106]:
#example usage
sum_gain = column_sums(Gain_matrix)
# Printing the result
print("Column sums of the gain matrix:\n", sum_gain)

Column sums of the gain matrix:
 [3.11063198e-04 2.86282048e-05 9.35701684e-05 6.64412589e-05]


In [107]:
#Converting noise to linear
D=10**6
N = -174 + 10 * math.log10(D) #noise in dbm
linear_noise = calculate_linear_trans_power([N])
print("Linear noise:", linear_noise)

Linear noise: [3.98107171e-15]


In [113]:
def calculate_formula_and_sums(result_scenarios_linear, sum_gain, linear_noise):
    a = np.array(result_scenarios_linear)
    b = np.array(sum_gain)
    bit_rate_matrix = (D * np.log2(1 + ((a * b) / linear_noise)))
#     row_sums = np.sum(bit_rate_matrix, axis=1)
    return bit_rate_matrix



In [117]:
#Usage
bitrate=calculate_formula_and_sums(result_scenarios_linear, sum_gain, linear_noise)
print(bitrate)

# print("Sum of each row:")
# for i, row_sum in enumerate(row_sums_bitrate):
#     print(f"{row_sum}")
    
# print(row_sums_bitrate)

[[26219475.63784241 22777777.21560425 24486388.51816297 23992419.30192096]
 [26219475.63784241 22777777.21560425 24486388.51816297 24656804.88899677]
 [26219475.63784241 22777777.21560425 24486388.51816297 25321190.48784566]
 [26219475.63784241 22777777.21560425 25150774.11448807 23992419.30192096]
 [26219475.63784241 22777777.21560425 25150774.11448807 24656804.88899677]
 [26219475.63784241 22777777.21560425 25150774.11448807 25321190.48784566]
 [26219475.63784241 22777777.21560425 25815159.71917287 23992419.30192096]
 [26219475.63784241 22777777.21560425 25815159.71917287 24656804.88899677]
 [26219475.63784241 22777777.21560425 25815159.71917287 25321190.48784566]
 [26219475.63784241 23442162.76054334 24486388.51816297 23992419.30192096]
 [26219475.63784241 23442162.76054334 24486388.51816297 24656804.88899677]
 [26219475.63784241 23442162.76054334 24486388.51816297 25321190.48784566]
 [26219475.63784241 23442162.76054334 25150774.11448807 23992419.30192096]
 [26219475.63784241 23442

In [130]:
def row_wise_sums(matrix):
    return [sum(row) for row in matrix]

In [131]:
row_sum_bitrate = row_wise_sums(bitrate)
print(*row_sum_bitrate, sep='\n')

97476060.67353058
98140446.26060641
98804831.85945529
98140446.26985568
98804831.85693151
99469217.45578039
98804831.87454048
99469217.46161631
100133603.06046519
98140446.21846968
98804831.80554548
99469217.40439437
98804831.81479478
99469217.40187058
100133603.00071947
99469217.41947955
100133603.00655538
100797988.60540426
98804831.79073209
99469217.37780792
100133602.9766568
99469217.38705719
100133602.97413301
100797988.5729819
100133602.99174199
100797988.57881778
101462374.17766668
98140446.28569406
98804831.87276986
99469217.47161876
98804831.88201916
99469217.46909496
100133603.06794386
99469217.48670393
100133603.07377976
100797988.67262864
98804831.83063313
99469217.41770896
100133603.01655784
99469217.42695823
100133603.01403406
100797988.61288294
100133603.03164303
100797988.61871886
101462374.21756774
99469217.40289554
100133602.98997137
100797988.58882025
100133602.99922064
100797988.58629647
101462374.18514535
100797988.60390544
101462374.19098127
102126759.78983015
988

In [132]:
def calculate_average(row_sums_bitrate):
    return np.mean(row_sums_bitrate)


In [133]:
average = calculate_average(row_sum_bitrate)
print("Average of  Bitrate:", average)

Average of  Bitrate: 100133603.03069098


In [134]:
row_sum_linear_scenario = row_wise_sums(result_scenarios_linear)
print(*row_sum_linear_scenario, sep='\n')

0.004
0.0045848931924611135
0.00551188643150958
0.0045848931924611135
0.005169786384922227
0.006096779623970694
0.00551188643150958
0.006096779623970694
0.007023772863019161
0.0045848931924611135
0.005169786384922227
0.006096779623970694
0.005169786384922227
0.00575467957738334
0.006681672816431807
0.006096779623970694
0.006681672816431807
0.007608666055480274
0.00551188643150958
0.006096779623970694
0.007023772863019161
0.006096779623970694
0.006681672816431807
0.007608666055480274
0.007023772863019161
0.007608666055480274
0.008535659294528741
0.0045848931924611135
0.005169786384922227
0.006096779623970694
0.005169786384922227
0.00575467957738334
0.006681672816431807
0.006096779623970694
0.006681672816431807
0.007608666055480274
0.005169786384922228
0.005754679577383341
0.006681672816431808
0.005754679577383341
0.006339572769844455
0.0072665660088929215
0.006681672816431808
0.0072665660088929215
0.00819355924794139
0.006096779623970694
0.006681672816431807
0.007608666055480274
0.00668

In [136]:
def constrained_optimization_algorithm(scenarios_in_linear, total_bitrate, average  ):
    
    

IndentationError: expected an indented block (3623249874.py, line 3)

In [ ]:
scenarios = [
        [0.001, 0.001, 0.001, 0.001],
        [0.001, 0.001, 0.001, 0.00158489],
        [0.001, 0.001, 0.001, 0.00251189],
        [0.001, 0.001, 0.00158489, 0.001],
        [0.001, 0.001, 0.00158489, 0.00158489],
        [0.001, 0.001, 0.00158489, 0.00251189]
    ]
row_sums = [
    [0.004],
    [0.00458489],
    [0.00551189],
    [0.00458489],
    [0.00516878],
    [0.00609578]
]

total_bitrate_matrix = [
    [4000000.0001460826],
    [4000000.0001848647],
    [4000000.0002463306],
    [4000000.000159239],
    [4000000.000198021],
    [4000000.000259487]
]

average_bitrate = 4000000.0001996185


# Initialize lowest_bitrate to be infinity
lowest_bitrate = float('inf')

# Iterate over the row_sums and total_bitrate_matrix simultaneously
for i, (row_sum, total_bitrate) in enumerate(zip(row_sums, total_bitrate_matrix)):
    # Check if the total bitrate is greater than or equal to the average bitrate
    if total_bitrate[0] >= average_bitrate:
        # Check if the row sum is less than the current lowest bitrate
        if row_sum[0] < lowest_bitrate:
            # Update the lowest bitrate, lowest bitrate scenario, and lowest bitrate scenario's power values
            lowest_bitrate = row_sum[0]
            lowest_bitrate_scenario = i+1
            lowest_bitrate_scenario_powers = scenarios[i]

# Print the lowest bitrate scenario, bitrate, and the power values used to obtain the lowest bitrate
if lowest_bitrate_scenario:
    print(f"Lowest possible bitrate scenario: {lowest_bitrate_scenario}")
    print(f"Lowest possible bitrate: {lowest_bitrate}")
    print(f"Power values used for the lowest bitrate scenario: {lowest_bitrate_scenario_powers}")
else:
    print("No scenario achieves a total bitrate greater than or equal to the average bitrate.")
