In [41]:
#imports
import math
import numpy as np
import random
import itertools

In [42]:
#constants
D=10**6  #Bandwodth
N= -174+10*(math.log10(D))  #Noise in DBM
N_linear=(N)*(10**(-3))*(10**(N/10))    #Noise in miliwatt


In [48]:
population = [0, 2, 4]
linear_power_values=calculate_linear_trans_power(population)
rounded_values = np.round(linear_power_values, 5)
print(rounded_values)

[0.001   0.00158 0.00251]


In [51]:
import itertools
import numpy as np

def generate_all_scenarios(powers, no_of_users):
    combinations = list(itertools.product(powers, repeat=no_of_users))
    return combinations

def calculate_linear_trans_power(population):
    return pow(10, -3) * np.power(10.0, np.array(population, dtype="float") / 10)

def print_linear_power_values(scenarios):
    for index, scenario in enumerate(scenarios, start=1):
        linear_power_values = calculate_linear_trans_power(scenario)
        print(f"{index}. {scenario} => {linear_power_values}")

# Example usage
powers = [0, 2, 4]  #in dbm
no_of_users = 4
scenarios = generate_all_scenarios(powers, no_of_users)
print_linear_power_values(scenarios)


1. (0, 0, 0, 0) => [0.001 0.001 0.001 0.001]
2. (0, 0, 0, 2) => [0.001      0.001      0.001      0.00158489]
3. (0, 0, 0, 4) => [0.001      0.001      0.001      0.00251189]
4. (0, 0, 2, 0) => [0.001      0.001      0.00158489 0.001     ]
5. (0, 0, 2, 2) => [0.001      0.001      0.00158489 0.00158489]
6. (0, 0, 2, 4) => [0.001      0.001      0.00158489 0.00251189]
7. (0, 0, 4, 0) => [0.001      0.001      0.00251189 0.001     ]
8. (0, 0, 4, 2) => [0.001      0.001      0.00251189 0.00158489]
9. (0, 0, 4, 4) => [0.001      0.001      0.00251189 0.00251189]
10. (0, 2, 0, 0) => [0.001      0.00158489 0.001      0.001     ]
11. (0, 2, 0, 2) => [0.001      0.00158489 0.001      0.00158489]
12. (0, 2, 0, 4) => [0.001      0.00158489 0.001      0.00251189]
13. (0, 2, 2, 0) => [0.001      0.00158489 0.00158489 0.001     ]
14. (0, 2, 2, 2) => [0.001      0.00158489 0.00158489 0.00158489]
15. (0, 2, 2, 4) => [0.001      0.00158489 0.00158489 0.00251189]
16. (0, 2, 4, 0) => [0.001      0.00158

In [50]:
#Creating Gain Matrix
def channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users):
    channel_matrix = np.zeros((num_users, num_BS_antenna), dtype=complex)
    
    for i in range(num_users):
        d = random.randint(min_distance, max_distance)  # random distance
        path_loss_factor = d ** (-loss)
        
        for j in range(num_BS_antenna):
            channel_coefficient = path_loss_factor * (np.random.randn() + 1j * np.random.randn()) / np.sqrt(2)
            channel_matrix[i][j] = channel_coefficient
            
    gain_matrix = np.abs(channel_matrix) ** 2
    return channel_matrix, gain_matrix

# Example usage
min_distance = 500
max_distance = 1000
loss = 4
num_BS_antenna = 4
num_users = 4

channel_mat, gain_matrix = channel_matrix(min_distance, max_distance, loss, num_BS_antenna, num_users)

channel_mat_array=np.array(channel_mat)  #Printing chaneel Matrix
print("Channel matrix:\n", channel_mat_array)   #converting the matrix to array

gain_matrix_array=np.array(gain_matrix)   #Printing Gain Matrix
print("Gain matrix:\n", gain_matrix_array)     #converting the matrix to array


Channel matrix:
 [[ 1.56883252e-12+1.89430508e-12j -1.12532619e-12-6.14267477e-15j
  -7.08702614e-13-1.88268653e-12j  9.30897799e-13-2.45813320e-12j]
 [ 1.81748906e-11+4.33378180e-12j -1.66230729e-11+1.33865531e-11j
   7.14195342e-12-2.52061025e-11j  1.95893562e-12-9.10645442e-12j]
 [-6.27317478e-12+3.82988980e-12j -5.76788024e-12-6.38299084e-12j
  -1.85401113e-12+1.13347531e-11j -8.53924063e-12+2.68030008e-12j]
 [ 2.37459288e-12+1.54189418e-11j  5.27370590e-12-6.87775516e-12j
  -6.76371227e-12-5.92823045e-12j -7.27144062e-12-5.23033934e-13j]]
Gain matrix:
 [[6.04962721e-24 1.26639678e-24 4.04676798e-24 6.90898953e-24]
 [3.49108313e-22 4.55526357e-22 6.86355102e-22 8.67649408e-23]
 [5.40207777e-23 7.40110145e-23 1.31913985e-22 8.01026391e-23]
 [2.43382458e-22 7.51154899e-23 8.08917200e-23 5.31474133e-23]]


In [ ]:
# first_row_random_matrix_array = random_matrix_array[0][0]
# print (first_row_random_matrix_array)


In [ ]:
# for j in range(gain_matrix_array.shape[1]):
#     column = gain_matrix_array[:,j]
#     print(column)


# first_column=gain_matrix_array[:, 0]
# print (first_column)

In [ ]:
# Result=first_row_random_matrix_array*first_column
# print(Result)


In [ ]:
# final = 1+((1 / N_linear)*Result)
# print(final)


In [ ]:
# Final_ = np.log2(final)
# print(D*Final_)

In [25]:
# Function to multiply a row with corresponding columns
def multiply_row_with_columns(row, matrix):
    results = []
    for i, element in enumerate(row):
        column = [row[i] for row in matrix]
        result = [element * col_element for col_element in column]
        results.append(result)
    return results

# Define the row indices you want to use for the multiplication
row_indices = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,
               40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
               50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
               60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
               70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]  # You can extend this list to include more row indices

# Initialize an empty list to store the results
all_results = []

# Multiply each element of the specified rows with the corresponding columns
for row_idx in row_indices:
    row = random_matrix_array[row_idx]
    results = multiply_row_with_columns(row, gain_matrix_array)
    all_results.append(results)

# Print the results
for idx, results in enumerate(all_results):
    row_idx = row_indices[idx]
    print(f"Results for row {row_idx + 1}:")
    for i, result in enumerate(results):
        print(f"  Element {i + 1} of the row multiplied with the corresponding column:")
        print(f"  {result}")
    print()


NameError: name 'random_matrix_array' is not defined

In [ ]:
for idx, results in enumerate(all_results):
    row_idx = row_indices[idx]
    print(f"Results for row {row_idx + 1}:")
    for i, result in enumerate(results):
        Final_Result= [D*(math.log2((1+(1/N_linear)*value))) for value in result]
        print(f"  Element {i + 1} of the row multiplied with the corresponding column:")
        print(f"  {Final_Result}")  # Add 2 to each element when printing
    print()

In [ ]:
# Function to sum the resulting matrices for a specific row
def sum_resulting_matrices(row_idx, all_results):
    return np.sum(all_results[row_idx], axis=0)

# Perform addition on many resulting matrices
for row_idx in row_indices:
    sum_result = sum_resulting_matrices(row_idx, all_results)
    print(f"Sum of the resulting matrices for row {row_idx + 1}: {sum_result}")